"""add madhhab

Revision ID: 4339354bfb0d
Revises: 4a012ad378f4
Create Date: 2026-08-18 14:19:23.482278

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4339354bfb0d'
down_revision: str | Sequence[str] | None = '4a012ad378f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shamela_collections', sa.Column('madhhab', sa.String(length=32), nullable=True))
    op.add_column('works', sa.Column('madhhab', sa.String(length=32), nullable=True))
    op.create_index('ix_works_tradition', 'works', ['tradition'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_works_tradition', table_name='works')
    op.drop_column('works', 'madhhab')
    op.drop_column('shamela_collections', 'madhhab')
    # ### end Alembic commands ###
