"""server defaults for not-null columns

Revision ID: 4a012ad378f4
Revises: 6084bf90ac0c
Create Date: 2026-08-18 14:11:50.087665

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a012ad378f4'
down_revision: str | Sequence[str] | None = '6084bf90ac0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('books', 'content_version',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('books', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('shamela_collections', 'book_count',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('subjects', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('works', 'volume_count',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('works', 'total_content_bytes',
               existing_type=sa.BIGINT(),
               server_default='0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'total_content_bytes',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('works', 'volume_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subjects', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shamela_collections', 'book_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('books', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('books', 'content_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('books', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
