"""nulls not distinct on author and work uniqueness

Revision ID: 5352cd4b99ea
Revises: 28c30c834b6f
Create Date: 2026-08-18 14:52:47.244782

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5352cd4b99ea'
down_revision: str | Sequence[str] | None = '28c30c834b6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_authors_name_death'), 'authors', type_='unique')
    op.create_unique_constraint('uq_authors_name_death', 'authors', ['name_norm', 'death_label'], postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('uq_works_title_author'), 'works', type_='unique')
    op.create_unique_constraint('uq_works_title_author', 'works', ['title_norm', 'author_id'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_works_title_author', 'works', type_='unique')
    op.create_unique_constraint(op.f('uq_works_title_author'), 'works', ['title_norm', 'author_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_authors_name_death', 'authors', type_='unique')
    op.create_unique_constraint(op.f('uq_authors_name_death'), 'authors', ['name_norm', 'death_label'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
