"""library schema

Revision ID: 813311c1675b
Revises: 0a0d7db79000
Create Date: 2026-08-18 14:07:13.723021

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '813311c1675b'
down_revision: str | Sequence[str] | None = '0a0d7db79000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



# PostgreSQL named enum types outlive the tables that use them: a CREATE TABLE creates the
# type implicitly, but DROP TABLE does not remove it. Left implicit, an
# upgrade → downgrade → upgrade cycle fails with DuplicateObjectError. Declaring them here
# with create_type=False and managing them explicitly makes the migration reversible.
TRADITION = postgresql.ENUM(
    "shia", "sunni", "zaydi", "shared", name="tradition", create_type=False
)
BOOK_FORMAT = postgresql.ENUM(
    "book", "manuscript", "journal", "diwan", "dictionary", "index",
    name="book_format", create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    TRADITION.create(op.get_bind(), checkfirst=True)
    BOOK_FORMAT.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=False),
    sa.Column('death_label', sa.String(length=64), nullable=True),
    sa.Column('death_year_hijri', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_norm', 'death_label', name='uq_authors_name_death')
    )
    op.create_index('ix_authors_name_norm', 'authors', ['name_norm'], unique=False)
    op.create_table('import_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ok','skipped','failed')", name='ck_import_log_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_log_book', 'import_log', ['book_id'], unique=False)
    op.create_index('ix_import_log_run', 'import_log', ['run_id'], unique=False)
    op.create_index('ix_import_log_status', 'import_log', ['status'], unique=False)
    op.create_table('languages',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shamela_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=True),
    sa.Column('tradition', TRADITION, nullable=True),
    sa.Column('format', BOOK_FORMAT, nullable=True),
    sa.Column('language_hint', sa.String(length=8), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_hint'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw')
    )
    op.create_index('ix_shamela_collections_normalized', 'shamela_collections', ['normalized'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_norm', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.String(length=32), nullable=True),
    sa.Column('tradition', TRADITION, nullable=True),
    sa.Column('format', BOOK_FORMAT, nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('volume_count', sa.Integer(), nullable=False),
    sa.Column('total_content_bytes', sa.BigInteger(), nullable=False),
    sa.Column('grouping_warning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_norm', 'author_id', name='uq_works_title_author')
    )
    op.create_index('ix_works_author', 'works', ['author_id'], unique=False)
    op.create_index('ix_works_subject', 'works', ['subject_id'], unique=False)
    op.create_index('ix_works_title_norm', 'works', ['title_norm'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_norm', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('edition', sa.Text(), nullable=True),
    sa.Column('published_year', sa.Text(), nullable=True),
    sa.Column('printer', sa.Text(), nullable=True),
    sa.Column('editor', sa.Text(), nullable=True),
    sa.Column('isbn', sa.Text(), nullable=True),
    sa.Column('source_pdf', sa.Text(), nullable=True),
    sa.Column('identity_notes', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('content_path', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('content_bytes', sa.BigInteger(), nullable=True),
    sa.Column('download_bytes', sa.BigInteger(), nullable=True),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('page_first', sa.Integer(), nullable=True),
    sa.Column('page_last', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('paragraph_count', sa.Integer(), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('volume IS NULL OR volume > 0', name='ck_books_volume_positive'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['shamela_collections.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_books_author', 'books', ['author_id'], unique=False)
    op.create_index('ix_books_collection', 'books', ['collection_id'], unique=False)
    op.create_index('ix_books_language', 'books', ['language_code'], unique=False)
    op.create_index('ix_books_published', 'books', ['is_published'], unique=False, postgresql_where='is_published')
    op.create_index('ix_books_title_norm', 'books', ['title_norm'], unique=False)
    op.create_index('ix_books_work', 'books', ['work_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_norm', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'ord', name='uq_sections_book_ord')
    )
    op.create_index('ix_sections_book', 'sections', ['book_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('paragraph_offsets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', arabic_normalize(text))", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'page_no', name='uq_pages_book_page')
    )
    op.create_index('ix_pages_book', 'pages', ['book_id'], unique=False)
    op.create_index('ix_pages_search_tsv', 'pages', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_pages_section', 'pages', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pages_section', table_name='pages')
    op.drop_index('ix_pages_search_tsv', table_name='pages', postgresql_using='gin')
    op.drop_index('ix_pages_book', table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_sections_book', table_name='sections')
    op.drop_table('sections')
    op.drop_index('ix_books_work', table_name='books')
    op.drop_index('ix_books_title_norm', table_name='books')
    op.drop_index('ix_books_published', table_name='books', postgresql_where='is_published')
    op.drop_index('ix_books_language', table_name='books')
    op.drop_index('ix_books_collection', table_name='books')
    op.drop_index('ix_books_author', table_name='books')
    op.drop_table('books')
    op.drop_index('ix_works_title_norm', table_name='works')
    op.drop_index('ix_works_subject', table_name='works')
    op.drop_index('ix_works_author', table_name='works')
    op.drop_table('works')
    op.drop_index('ix_shamela_collections_normalized', table_name='shamela_collections')
    op.drop_table('shamela_collections')
    op.drop_table('subjects')
    op.drop_table('languages')
    op.drop_index('ix_import_log_status', table_name='import_log')
    op.drop_index('ix_import_log_run', table_name='import_log')
    op.drop_index('ix_import_log_book', table_name='import_log')
    op.drop_table('import_log')
    op.drop_index('ix_authors_name_norm', table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
    BOOK_FORMAT.drop(op.get_bind(), checkfirst=True)
    TRADITION.drop(op.get_bind(), checkfirst=True)
